# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Parking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'YandexMapsMobile', '4.1.0-full'

end
